Models/Sensor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FYP_Smiley.Models
{
    public partial class Sensor
    {
        public Sensor()
        {
            SensorData = new HashSet<SensorData>();
        }

        public int SensorId { get; set; }

        [Required(ErrorMessage = "Access Point Id is required")]
        public int AccessPointId { get; set; }

        [Required(ErrorMessage = "Sensor Name is required")]
        public string SensorName { get; set; }

        public virtual AccessPoint AccessPoint { get; set; }
        public virtual ICollection<SensorData> SensorData { get; set; }
    }
}

Controllers/SensorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class SensorController : Controller
    {
        private AppDbContext _dbContext;

        public SensorController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<Sensor> dbs = _dbContext.Sensor;
            List<Sensor> model = dbs.ToList();

            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            DbSet<Sensor> dbs = _dbContext.Sensor;
            var lstPokes = dbs.ToList();
            ViewData["pokes"] = new SelectList(lstPokes, "FacilityId", "Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Sensor sensor)
        {
            if (ModelState.IsValid)
            {
                DbSet<Sensor> dbs = _dbContext.Sensor;
                dbs.Add(sensor);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Sensor added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Update(int id)
        {
            DbSet<Sensor> dbs = _dbContext.Sensor;
            Sensor tOrder = dbs.Where(mo => mo.SensorId == id).FirstOrDefault();

            return View(tOrder);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(Sensor sensor)
        {
            if (ModelState.IsValid)
            {
                DbSet<Sensor> dbs = _dbContext.Sensor;
                Sensor tOrder = dbs.Where(mo => mo.SensorId == sensor.SensorId)
                                     .FirstOrDefault();

                if (tOrder != null)
                {
                    tOrder.SensorId = sensor.SensorId;
                    tOrder.AccessPointId = sensor.AccessPointId;
                    tOrder.SensorName = sensor.SensorName;

                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Sensor updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Sensor not found!";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<Sensor> dbs = _dbContext.Sensor;

            Sensor tOrder = dbs.Where(mo => mo.SensorId == id).FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Sensor deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Sensor not found!";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<Sensor> dbs = _dbContext.Sensor;
            List<Sensor> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Record not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Views/Sensor/Create.cshtml
@model Sensor

@{
    ViewData["Title"] = "New Sensor";
}

@section ScriptSection {
    <script>

        $(document).ready(function () {

            $("form").submit(function () {
                if (confirm("Proceed? Press OK to confirm.") == false) {
                    event.preventDefault();   // not working in IE
                    event.stopPropagation();  // not working in Firefox
                    return false;             // working in IE
                };
            });
        });

    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="Sensor" asp-action="Create" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">

                <partial name="_Sensor" />

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>

Views/Sensor/Index.cshtml
@model List<Sensor>

@{
    ViewBag.Title = "Sensor";
}

@section ScriptSection {
    <script>
        function ConfirmDelete() {
            if (confirm("Are you sure you want to delete?") == false) {
                event.preventDefault();   // not working in IE
                event.stopPropagation();  // not working in Firefox
                return false;             // working in IE
            }
        }

    </script>
}
<h2>Sensor</h2>

<span style="color:red">@TempData["Msg"]</span>
<br />
<p>
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="Sensor" asp-action="Create">Create New</a>
    }
</p>

<a asp-action="Print" target="_blank">Print</a>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Access Point</th>
        @if (User.IsInRole("Admin"))
        {
            <th>Action</th>
        }

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SensorId</td>
            <td>@item.SensorName</td>
            <td>@item.AccessPointId</td>

            @if (User.IsInRole("Admin"))
            {
                 <td>
                <a asp-action="Update" asp-route-id="@item.SensorId">Update | </a>
                <a asp-action="Delete" asp-route-id="@item.SensorId" onclick="return ConfirmDelete()">Delete</a>
            </td>
            }
           

        </tr>
    }
</table>

Views/Sensor/Print.cshtml
@model List<Sensor>
@{
    Layout = null;
}

<html>
<head>
    <meta charset="utf-8">
    <title>Sensor Record</title>
    <style>
        .label {
            font-size: large;
            font-weight: bold;
            font-family: Arial;
        }

        .item {
            font-size: large;
            font-family: Arial;
        }

        .lineitem {
            height: 1cm;
        }
    </style>
</head>

<body>
    <header>
        <table style="border-width:thick;width:100%">
            <tr>
                <td style="width:3cm"><img src="~/images/Smiley pink logo .png" style="width:3cm"></td>
                <td style="width:1cm"></td>
                <td>
                    <h1>Sensor Record</h1>
                    <address>
                        <p>
                            <span style="font-size:x-large;font-family:'Bookman Old Style'">Smiley</span><br />
                        </p>
                    </address>
                </td>

            </tr>
        </table>
    </header>
    <hr />
    <article style="border:solid">
        <table style="width:100%">
            <tr>
                <th>Sensor ID</th>
                <th>Access Point ID</th>
                <th>Sensor Name</th>
            </tr>


            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.SensorId</td>
                    <td>@item.AccessPointId</td>
                    <td>@item.SensorName</td>
                </tr>
            }
        </table>
    </article>

</body>
</html>  

Views/Sensor/Update.cshtml
@model Sensor

@{
    ViewData["Title"] = "Update Sensor";
}

@section ScriptSection {
    <script>

        $(document).ready(function () {
            $("form").submit(function () {
                confirm("Proceed? Press OK to confirm.");
            });
        });

    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <form asp-controller="Sensor" asp-action="Update" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">

                <div class="form-group">
                    <label asp-for="SensorId" class="col-sm-3 control-label">Sensor Id</label>
                    <div class="col-sm-6">
                        <input id="txtSI" asp-for="SensorId" class="form-control" />
                    </div>

                </div>

                <partial name="_Sensor" />

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>