Models/AccessPoint.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FYP_Smiley.Models
{
    public partial class AccessPoint
    {
        public AccessPoint()
        {
            Authorisation = new HashSet<Authorisation>();
            Sensor = new HashSet<Sensor>();
        }

        public int AccessPointId { get; set; }

        [Required(ErrorMessage = "FacilityId is required")]
        public int FacilityId { get; set; }

        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        public virtual Facility Facility { get; set; }
        public virtual ICollection<Authorisation> Authorisation { get; set; }
        public virtual ICollection<Sensor> Sensor { get; set; }
    }
}

Controllers/AccessLogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class AccessLogController : Controller
    {
        private AppDbContext _dbContext;

        public AccessLogController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<AccessLog> dbs = _dbContext.AccessLog;
            List<AccessLog> model = dbs.ToList();

            return View(model);
        }


        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<AccessLog> dbs = _dbContext.AccessLog;
            List<AccessLog> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Log not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Controllers/AccessPointController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class AccessPointController : Controller
    {
        private AppDbContext _dbContext;

        public AccessPointController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
            List<AccessPoint> model = dbs.ToList();
       
            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
            var lstPokes = dbs.ToList();
            ViewData["pokes"] = new SelectList(lstPokes, "FacilityId", "Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(AccessPoint accessPoint)
        {
            if (ModelState.IsValid)
            {
                DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
                dbs.Add(accessPoint);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New access point added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Update(int id)
        {
            DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
            AccessPoint tOrder = dbs.Where(mo => mo.AccessPointId == id).FirstOrDefault();

                return View(tOrder);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(AccessPoint accessPoint)
        {
            if (ModelState.IsValid)
            {
                DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
                AccessPoint tOrder = dbs.Where(mo => mo.AccessPointId == accessPoint.AccessPointId).FirstOrDefault();

                if (tOrder != null)
                {
                    tOrder.AccessPointId = accessPoint.AccessPointId;
                    tOrder.FacilityId = accessPoint.FacilityId;
                    tOrder.Description = accessPoint.Description;

                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Access Point updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }

                else
                {
                    TempData["Msg"] = "Access Point not found!";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<AccessPoint> dbs = _dbContext.AccessPoint;

            AccessPoint tOrder = dbs.Where(mo => mo.AccessPointId == id).FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Access Point deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Access Point not found!";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<AccessPoint> dbs = _dbContext.AccessPoint;
            List<AccessPoint> model = dbs.ToList() ;

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Record not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Controllers/AuthorisationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class AuthorisationController : Controller
    {
        private AppDbContext _dbContext;

        public AuthorisationController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<Authorisation> dbs = _dbContext.Authorisation;
            List<Authorisation> model = dbs.ToList();

            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            DbSet<Authorisation> dbs = _dbContext.Authorisation;
            var lstPokes = dbs.ToList();
            ViewData["pokes"] = new SelectList(lstPokes, "FacilityId", "Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Authorisation authorisation)
        {
            if (ModelState.IsValid)
            {
                DbSet<Authorisation> dbs = _dbContext.Authorisation;
                dbs.Add(authorisation);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Authorisation added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Update(int id)
        {
            DbSet<Authorisation> dbs = _dbContext.Authorisation;
            Authorisation tOrder = dbs.Where(mo => mo.AccessPointId == id).FirstOrDefault();

            return View(tOrder);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(Authorisation authorisation)
        {
            if (ModelState.IsValid)
            {
                DbSet<Authorisation> dbs = _dbContext.Authorisation;
                Authorisation tOrder = dbs.Where(mo => mo.AccessPointId == authorisation.AccessPointId)
                                     .FirstOrDefault();

                if (tOrder != null)
                {
                    tOrder.AccessPointId = authorisation.AccessPointId;
                    tOrder.StartDate = authorisation.StartDate;
                    tOrder.EndDate = authorisation.EndDate;
                    tOrder.UserId = authorisation.UserId;

                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Authorisation updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Authorisation not found!";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            DbSet<Authorisation> dbs = _dbContext.Authorisation;

            Authorisation tOrder = dbs.Where(mo => mo.AccessPointId == id).FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Authorisation deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Authorisation not found!";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<Authorisation> dbs = _dbContext.Authorisation;
            List<Authorisation> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Record not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Controllers/FacilityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class FacilityController : Controller
    {
        private AppDbContext _dbContext;

        public FacilityController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<Facility> dbs = _dbContext.Facility;
            List<Facility> model = dbs.ToList();

            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            DbSet<Facility> dbs = _dbContext.Facility;
            var lstPokes = dbs.ToList();
            ViewData["pokes"] = new SelectList(lstPokes, "FacilityId", "Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Facility facility)
        {
            if (ModelState.IsValid)
            {
                DbSet<Facility> dbs = _dbContext.Facility;
                dbs.Add(facility);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Facility added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Update(int id)
        {
            DbSet<Facility> dbs = _dbContext.Facility;
            Facility tOrder = dbs.Where(mo => mo.FacilityId == id).FirstOrDefault();

            return View(tOrder);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(Facility facility)
        {
            if (ModelState.IsValid)
            {
                DbSet<Facility> dbs = _dbContext.Facility;
                Facility tOrder = dbs.Where(mo => mo.FacilityId == facility.FacilityId)
                                     .FirstOrDefault();

                if (tOrder != null)
                {
                    tOrder.FacilityId = facility.FacilityId;
                    tOrder.AdminId = facility.AdminId;
                    tOrder.FacilityName = facility.FacilityName;
                    tOrder.PostalCode = facility.PostalCode;
                    tOrder.BlockNumber = facility.BlockNumber;
                    tOrder.StreetName = facility.StreetName;
                    tOrder.BannerPic = facility.BannerPic;

                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Facility updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Facility not found!";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            DbSet<Facility> dbs = _dbContext.Facility;

            Facility tOrder = dbs.Where(mo => mo.FacilityId == id).FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Facility deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Facility not found!";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<Facility> dbs = _dbContext.Facility;
            List<Facility> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Record not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Controllers/SensorDataController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FYP_Smiley.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;

namespace FYP_Smiley.Controllers
{
    public class SensorDataController : Controller
    {
        private AppDbContext _dbContext;

        public SensorDataController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<SensorData> dbs = _dbContext.SensorData;
            List<SensorData> model = dbs.ToList();

            return View(model);
        }


        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<SensorData> dbs = _dbContext.SensorData;
            List<SensorData> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {
                    PageSize = Rotativa.AspNetCore.Options.Size.B5,
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
                };
            else
            {
                TempData["Msg"] = "Sensor Data not found!";
                return RedirectToAction("Index");
            }

        }

    }
}

Views/Shared/_AccessPoint.cshtml
@model AccessPoint
@{
    var a = ViewData["pokes"];
}

<div class="form-group">


    <label asp-for="FacilityId" class="col-sm-3 control-label">Facility Id</label>

    <div class="col-sm-6">
        <input id="txtFac" asp-for="FacilityId" class="form-control" />
    </div>

    <div class="col-sm-6">
        <span asp-validation-for="FacilityId" class="text-danger"></span>
    </div>

</div>

<div class="form-group">
    <label asp-for="Description" class="col-sm-3 control-label">
        Description
    </label>
    <div class="col-sm-6">
        <input id="txtDesc" asp-for="Description" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
</div>

Views/Shared/_Authorisation.cshtml
@model Authorisation
@{
    var a = ViewData["pokes"];
}

<div class="form-group">
    <label asp-for="StartDate" class="col-sm-3 control-label">Start Date</label>
    <div class="col-sm-6">
        <input id="txtStart" asp-for="StartDate" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="EndDate" class="col-sm-3 control-label">
        End Date
    </label>
    <div class="col-sm-6">
        <input id="txtEnd" asp-for="EndDate" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
</div>

Views/Shared/_Facility.cshtml
@model Facility
@{
    var a = ViewData["pokes"];
}

<div class="form-group">
    <label asp-for="AdminId" class="col-sm-3 control-label">Admin Id</label>
    <div class="col-sm-6">
        <input id="txtAd" asp-for="AdminId" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="AdminId" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="FacilityName" class="col-sm-3 control-label">
        Facility Name
    </label>
    <div class="col-sm-6">
        <input id="txtFN" asp-for="FacilityName" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="FacilityName" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="PostalCode" class="col-sm-3 control-label">
        Postal Code
    </label>
    <div class="col-sm-6">
        <input id="txtPC" asp-for="PostalCode" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="PostalCode" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="BlockNumber" class="col-sm-3 control-label">
        Block Number
    </label>
    <div class="col-sm-6">
        <input id="txtBN" asp-for="BlockNumber" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="BlockNumber" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="StreetName" class="col-sm-3 control-label">
        Street Name
    </label>
    <div class="col-sm-6">
        <input id="txtSN" asp-for="StreetName" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="StreetName" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="BannerPic" class="col-sm-3 control-label">
        Banner
    </label>
    <div class="col-sm-6">
        <input id="txtBP" asp-for="BannerPic" class="form-control" />
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Smiley @ViewData["Title"]</title>

    <!-- style sheets references -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- script files references -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.min.js"></script>
    <script src="~/lib/jquery/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("ScriptSection", false)

    <style>

        nav {
            background-color: antiquewhite;
            font-family: Arial, Helvetica, sans-serif;
            color: black;
            height: 100px;
        }

        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
            color: black;
            background-color: antiquewhite;
            margin: 2px;
        }

    </style>

</head>

<body>
    <div class="row">
        <div class="col-2">
            <br />
            <a asp-controller="SmileyUser" asp-action="Index">
                <img src="~/images/smiley orange logo .png" style="width:100%" />
            </a>

            <br />
            <br />

            @if (User.Identity.IsAuthenticated)
            {
                <h4 class="text-center text-primary">
                    Welcome @User.Identity.Name
                </h4>
                <br />

                <h4 class="text-center text-primary">
                    <a asp-controller="SmileyUser" asp-action="Logoff" asp-route-returnUrl="SmileyUser/Login">Logout</a>
                </h4>

                <h4 class="text-center text-primary">
                    <a asp-controller="SmileyUser" asp-action="ChangePassword" asp-route-returnUrl="SmileyUser">Change Password</a>
                </h4>

                <h4 class="text-center text-primary">
                    <a asp-controller="SmileyUser" asp-action="Index" asp-route-returnUrl="SmileyUser">User</a>
                </h4>

            }
        </div>

        <div class="col-10">
            <div class="row">
                <nav class="navbar navbar-expand-lg col-12"  role="navigation">
                    <div>
                        <ul class="nav navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="AccessPoint">Access Point</a>
                                </li>

                                <li>
                                    <a class="nav-link" asp-action="Index" asp-controller="AccessLog">Access Log</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Facility">Facility</a>
                                </li>

                                <li>
                                    <a class="nav-link" asp-action="Index" asp-controller="Authorisation">Authorisation</a>
                                </li>


                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Sensor">Sensor</a>
                                </li>

                                <li>
                                    <a class="nav-link" asp-action="Index" asp-controller="SensorData">Sensor Data</a>
                                </li>


                            }

                        </ul>
                    </div>
                </nav>
            </div>

            <div class="row">
                <div class="col-10">
                    @RenderBody()
                </div>
                <div class="col-2"></div>
            </div>

        </div>
    </div>


</body>
</html>

Views/Shared/_Sensor.cshtml
@model Sensor
@{
    var a = ViewData["pokes"];
}

<div class="form-group">
    <label asp-for="AccessPointId" class="col-sm-3 control-label">Access Point Id</label>
    <div class="col-sm-6">
        <input id="txtFac" asp-for="AccessPointId" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="AccessPointId" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="SensorName" class="col-sm-3 control-label">
        Sensor Name
    </label>
    <div class="col-sm-6">
        <input id="txtDesc" asp-for="SensorName" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="SensorName" class="text-danger"></span>
    </div>
</div>

Views/Shared/_SmileyUser.cshtml
@model SmileyUser
@{
    var a = ViewData["pokes"];
}

<div class="form-group">
    <label asp-for="UserId" class="col-sm-3 control-label">User Id</label>
    <div class="col-sm-6">
        <input id="txtUI" asp-for="UserId" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="FullName" class="col-sm-3 control-label">Full Name</label>
    <div class="col-sm-6">
        <input id="txtFN" asp-for="FullName" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="Email" class="col-sm-3 control-label">
        Email
    </label>
    <div class="col-sm-6">
        <input id="txtE" asp-for="Email" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="Password" class="col-sm-3 control-label">
        Password
    </label>
    <div class="col-sm-6">
        <input id="txtP" asp-for="Password" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="Voicefile" class="col-sm-3 control-label">
        Voice File
    </label>
    <div class="col-sm-6">
        <input id="txtVF" asp-for="Voicefile" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Voicefile" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="Picfile" class="col-sm-3 control-label">
        Pic File
    </label>
    <div class="col-sm-6">
        <input id="txtPF" asp-for="Picfile" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Picfile" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="Role" class="col-sm-3 control-label">
        Role
    </label>
    <div class="col-sm-6">
        <input id="txtR" asp-for="Role" class="form-control" />
    </div>
    <div class="col-sm-6">
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
</div>

<div class="form-group">
    <label asp-for="PhoneNum" class="col-sm-3 control-label">
        Phone Number
    </label>
    <div class="col-sm-6">
        <input id="txtPN" asp-for="PhoneNum" class="form-control" />
    </div>
</div>