Models/SmileyUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FYP_Smiley.Models
{
    public partial class SmileyUser
    {
        public SmileyUser()
        {
            AccessLog = new HashSet<AccessLog>();
            Authorisation = new HashSet<Authorisation>();
            Facility = new HashSet<Facility>();
        }

        [Required(ErrorMessage = "User Id is required")]
        public string UserId { get; set; }

        [Required(ErrorMessage = "Full Name is required")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid date format")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public byte[] Password { get; set; }

        [Required(ErrorMessage = "Voice File is required")]
        public string Voicefile { get; set; }

        [Required(ErrorMessage = "Pic File is required")]
        public string Picfile { get; set; }

        [Required(ErrorMessage = "Role is required")]
        public string Role { get; set; }

        public string PhoneNum { get; set; }
        public DateTime? LastLogin { get; set; }

        public virtual ICollection<AccessLog> AccessLog { get; set; }
        public virtual ICollection<Authorisation> Authorisation { get; set; }
        public virtual ICollection<Facility> Facility { get; set; }
    }
}

Controllers/SmileyUserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Data;
using System.Security.Claims;
using FYP_Smiley.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using System.Dynamic;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace FYP_Smiley.Controllers
{
    public class SmileyUserController : Controller
    {
        private const string AUTHSCHEME = "UserSecurity";
        private const string LOGIN_SQL =
           @"SELECT * FROM Smiley_User 
            WHERE user_id = '{0}' 
              AND Password = HASHBYTES('SHA1', '{1}')";

        private const string LASTLOGIN_SQL =
           @"UPDATE Smiley_User SET last_login=GETDATE() 
                        WHERE user_id='{0}'";

        private const string ROLE_COL = "role";
        private const string NAME_COL = "full_name";

        private const string REDIRECT_CNTR = "Home";
        private const string REDIRECT_ACTN = "Index";

        private const string LOGIN_VIEW = "Login";

        private AppDbContext _dbContext;

        public SmileyUserController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            List<SmileyUser> model = dbs.ToList();

            return View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            var lstPokes = dbs.ToList();
            ViewData["pokes"] = new SelectList(lstPokes, "user_id", "full_Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(SmileyUser smileyUser)
        {
            if (ModelState.IsValid)
            {
                DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
                dbs.Add(smileyUser);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "New Smiley User added!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Update(string id)
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            SmileyUser tOrder = dbs.Where(mo => mo.UserId == id).FirstOrDefault();

            return View(tOrder);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(SmileyUser smileyUser)
        {
            if (ModelState.IsValid)
            {
                DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
                SmileyUser tOrder = dbs.Where(mo => mo.UserId == smileyUser.UserId)
                                     .FirstOrDefault();

                if (tOrder != null)
                {
                    tOrder.UserId = smileyUser.UserId;
                    tOrder.FullName = smileyUser.FullName;
                    tOrder.Email = smileyUser.Email;
                    tOrder.Password = smileyUser.Password;
                    tOrder.Voicefile = smileyUser.Voicefile;
                    tOrder.Picfile = smileyUser.Picfile;
                    tOrder.Role = smileyUser.Role;
                    tOrder.PhoneNum = smileyUser.PhoneNum;

                    if (_dbContext.SaveChanges() == 1)
                        TempData["Msg"] = "Smiley User updated!";
                    else
                        TempData["Msg"] = "Failed to update database!";
                }
                else
                {
                    TempData["Msg"] = "Smiley User not found!";
                    return RedirectToAction("Index");
                }
            }

            else
            {
                TempData["Msg"] = "Invalid information entered";
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(string id)
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;

            SmileyUser tOrder = dbs.Where(mo => mo.UserId == id).FirstOrDefault();

            if (tOrder != null)
            {
                dbs.Remove(tOrder);

                if (_dbContext.SaveChanges() == 1)
                    TempData["Msg"] = "Smiley User deleted!";
                else
                    TempData["Msg"] = "Failed to update database!";
            }
            else
            {
                TempData["Msg"] = "Smiley User not found!";
            }
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            TempData["ReturnUrl"] = returnUrl;
            return View(LOGIN_VIEW);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Login(LoginUser user)
        {
            if (!AuthenticateUser(user.UserId, user.Password, out ClaimsPrincipal principal))
            {
                ViewData["Message"] = "Incorrect User Id or Password";
                ViewData["MsgType"] = "warning";
                return View(LOGIN_VIEW);
            }
            else
            {
                HttpContext.SignInAsync(
                   AUTHSCHEME,
                   principal,
               new AuthenticationProperties
               {
                   IsPersistent = false
               });

                int num_affected = _dbContext.Database.ExecuteSqlInterpolated($"UPDATE Smiley_User SET last_login=GETDATE() WHERE user_id = {user.UserId}");

                if (TempData["returnUrl"] != null)
                {
                    string returnUrl = TempData["returnUrl"].ToString();
                    if (Url.IsLocalUrl(returnUrl))
                        return Redirect(returnUrl);
                }

                return RedirectToAction(REDIRECT_ACTN, REDIRECT_CNTR);
            }
        }

        [Authorize]
        public IActionResult Logoff(string returnUrl = null)
        {
            HttpContext.SignOutAsync(AUTHSCHEME);
            if (Url.IsLocalUrl(returnUrl))
                return Redirect(returnUrl);
            return RedirectToAction(REDIRECT_ACTN, REDIRECT_CNTR);
        }

        [AllowAnonymous]
        public IActionResult Forbidden()
        {
            return View();
        }

        private bool AuthenticateUser(string uid, string pw, out ClaimsPrincipal principal)
        {

            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            var pw_bytes = System.Text.Encoding.ASCII.GetBytes(pw);

            SmileyUser smileyUser = dbs.FromSqlInterpolated($"SELECT * FROM Smiley_User WHERE user_id = {uid} AND password = HASHBYTES('SHA1', {pw_bytes})").FirstOrDefault();

            principal = null;

            if (smileyUser != null)
            {
                principal =
                   new ClaimsPrincipal(
                      new ClaimsIdentity(
                         new Claim[] {
                        new Claim(ClaimTypes.NameIdentifier, smileyUser.UserId),
                        new Claim(ClaimTypes.Name, smileyUser.FullName),
                        new Claim(ClaimTypes.Role, smileyUser.Role)
                         }, "Basic"
                      )
                   );
                return true;
            }
            return false;
        }

        [Authorize]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult ChangePassword(PasswordUpdate pu)
        {
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var sql = String.Format($"UPDATE Smiley_User SET password = HASHBYTES('SHA1', '{pu.NewPassword}') WHERE user_id='{userid}' AND password = HASHBYTES('SHA1', '{pu.CurrentPassword}')");

            if (_dbContext.Database.ExecuteSqlCommand(sql) == 1)
                ViewData["Msg"] = "Password successfully updated!";
            else
                ViewData["Msg"] = "Failed to update password!";
            return View();
        }

        [Authorize]
        public JsonResult VerifyCurrentPassword(string CurrentPassword)
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var pw_bytes = System.Text.Encoding.ASCII.GetBytes(CurrentPassword);

            SmileyUser user = dbs.FromSqlInterpolated($"SELECT * FROM Smiley_User WHERE user_id = {userid} AND password = HASHBYTES('SHA1', {pw_bytes})").FirstOrDefault();

            if (user != null)
                return Json(true);
            else
                return Json(false);
        }

        [Authorize]
        public JsonResult VerifyNewPassword(string NewPassword)
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var pw_bytes = System.Text.Encoding.ASCII.GetBytes(NewPassword);

            SmileyUser user = dbs.FromSqlInterpolated($"SELECT * FROM Smiley_User WHERE user_id = {userid} AND password = HASHBYTES('SHA1', {pw_bytes})").FirstOrDefault();
            if (user == null)
                return Json(true);
            else
                return Json(false);
        }

        [Authorize]
        public IActionResult Print(int id)
        {
            DbSet<SmileyUser> dbs = _dbContext.SmileyUser;
            List<SmileyUser> model = dbs.ToList();

            if (model != null)
                return new ViewAsPdf(model)
                {

Views/SmileyUser/ChangePassword.cshtml
@model PasswordUpdate

@{
    ViewData["Title"] = "Change Password";
}

@section ScriptSection{
    <text>@ViewData["script"]</text>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <span style="color:red">@ViewData["Msg"]</span><br />
        <form asp-controller="Account" asp-action="ChangePassword" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div class="form-group">
                    <label asp-for="CurrentPassword" class="col-sm-3 control-label">Current Password:</label>
                    <div class="col-sm-6">
                        <input asp-for="CurrentPassword" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="NewPassword" class="col-sm-3 control-label">New Password:</label>
                    <div class="col-sm-6">
                        <input asp-for="NewPassword" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="col-sm-3 control-label">Confirm Password:</label>
                    <div class="col-sm-6">
                        <input asp-for="ConfirmPassword" class="form-control" />
                    </div>
                    <div class="has-error">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Views/SmileyUser/Create.cshtml
@model SmileyUser

@{
    ViewData["Title"] = "New Smiley User";
}

@section ScriptSection {
    <script>

        $(document).ready(function () {

            $("form").submit(function () {
                if (confirm("Proceed? Press OK to confirm.") == false) {
                    event.preventDefault();   // not working in IE
                    event.stopPropagation();  // not working in Firefox
                    return false;             // working in IE
                };
            });
        });

    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-6">
        <form asp-controller="SmileyUser" asp-action="Create" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">

                <partial name="_SmileyUser" />

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>

            </div>
        </form>
    </div>

</div>

Views/SmileyUser/Forbidden.cshtml
@{
    Layout = ViewData["Layout"] as string;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Forbidden</title>
</head>
<body>
    <h2>Forbidden</h2>
</body>
</html>

Views/SmileyUser/Index.cshtml
@model List<SmileyUser>

@{
    ViewBag.Title = "Smiley User";
}

@section ScriptSection {
    <script>
        function ConfirmDelete() {
            if (confirm("Are you sure you want to delete?") == false) {
                event.preventDefault();   // not working in IE
                event.stopPropagation();  // not working in Firefox
                return false;             // working in IE
            }
        }

    </script>
}
<h2>Smiley User</h2>

<span style="color:red">@TempData["Msg"]</span>
<br />
<p>
    @if (User.IsInRole("Admin"))
    {
        <a asp-controller="SmileyUser" asp-action="Create">Create New</a>
    }
</p>

<a asp-action="Print" target="_blank">Print</a>
<table class="table">
    <tr>
        <th>User Id</th>
        <th>Full Name</th>
        <th>Email</th>
        <th>Voicefile</th>
        <th>Picfile</th>
        <th>Role</th>
        <th>PhoneNum</th>
        <th>LastLogin</th>

        @if (User.IsInRole("Admin"))
        {
            <th>Actions</th>
        }

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.UserId</td>
            <td>@item.FullName</td>
            <td>@item.Email</td>
            <td>@item.Voicefile</td>
            <td>@item.Picfile</td>
            <td>@item.Role</td>
            <td>@item.PhoneNum</td>
            <td>@item.LastLogin</td>

             @if (User.IsInRole("Admin"))
             {
            <td>
                <a asp-action="Update" asp-route-id="@item.UserId">Update | </a>
                <a asp-action="Delete" asp-route-id="@item.UserId" onclick="return ConfirmDelete()">Delete</a>
            </td>
             }
 

        </tr>
    }
</table>

Views/SmileyUser/Login.cshtml
@model LoginUser
@{
    string msg = ViewData["Message"] as string;
}

<form class="form-horizontal" method="post">
    @if (msg != null)
    {
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-4">
                <div class="alert alert-danger">
                    <strong>@msg</strong>
                </div>
            </div>
        </div>
    }

    <div class="row h-100 justify-content-center">

        <br />
        <br />
        <div class="card col-sm-6 my-sm-auto" style="background-color: antiquewhite;
        color: black;
        border-color: antiquewhite;">
            <div class="card-body">
                <img src="~/images/Raspberry Pi (Orange v1) .png" style="width:100%" />
            </div>
        </div>

        <div class="col-sm-4 my-sm-auto">

            <div class="card" style=" background-color: antiquewhite;
                color: black;
                border-color: antiquewhite;
                padding-left: 2em;
                padding-left: 2em;
                padding-right: 2em;">

                <div class="card-body">
                    <h2 class="form-signin-heading">Please Login</h2>
                    <br />

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label asp-for="UserId" class="control-label">User ID :</label>
                            <input asp-for="UserId" class="form-control" placeholder="Your user id" />
                            <div class="has-error">
                                <span asp-validation-for="UserId" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label asp-for="Password" class="control-label">Password :</label>
                            <input asp-for="Password" class="form-control" placeholder="Password" />
                            <div class="has-error">
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                        </div>

                        <br />

                        <div class="form-group">
                            <input type="submit" class="btn btn-lg btn-primary btn-block" value="Sign In" />
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</form>

Views/SmileyUser/Print.cshtml
@model List<SmileyUser>
@{
    Layout = null;
}

<html>
<head>
    <meta charset="utf-8">
    <title>Smiley User Record</title>
    <style>
        .label {
            font-size: large;
            font-weight: bold;
            font-family: Arial;
        }

        .item {
            font-size: large;
            font-family: Arial;
        }

        .lineitem {
            height: 1cm;
        }
    </style>
</head>

<body>
    <header>
        <table style="border-width:thick;width:100%">
            <tr>
                <td style="width:3cm"><img src="~/images/Smiley pink logo .png" style="width:3cm"></td>
                <td style="width:1cm"></td>
                <td>
                    <h1>Smiley User Record</h1>
                    <address>
                        <p>
                            <span style="font-size:x-large;font-family:'Bookman Old Style'">Smiley</span><br />
                        </p>
                    </address>
                </td>
            </tr>
        </table>
    </header>
    <hr />
    <article style="border:solid">
        <table style="width:100%">
            <tr>
                <th>User Id</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Voicefile</th>
                <th>Picfile</th>
                <th>Role</th>
                <th>PhoneNum</th>
                <th>LastLogin</th>
            </tr>


            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.UserId</td>
                    <td>@item.FullName</td>
                    <td>@item.Email</td>
                    <td>@item.Voicefile</td>
                    <td>@item.Picfile</td>
                    <td>@item.Role</td>
                    <td>@item.PhoneNum</td>
                    <td>@item.LastLogin</td>
                </tr>
            }
        </table>
    </article>

</body>
</html>  

Views/SmileyUser/Update.cshtml
@model SmileyUser

@{
    ViewData["Title"] = "Update Smiley User";
}

@section ScriptSection {
    <script>

        $(document).ready(function () {
            $("form").submit(function () {
                confirm("Proceed? Press OK to confirm.");
            });
        });

    </script>
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-7">
        <form asp-controller="SmileyUser" asp-action="Update" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">

              

                <partial name="_SmileyUser" />

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-10">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>